language:
  - ruby
  - node_js

cache: bundler

before_install:
  - gem update --system
  - gem install bundler
  - npm install -g grunt-cli

install:
  - bundle install
  - npm install

script:
- grunt build

# blocklist
branches:
  except:
    - master
