# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: thoughtworksarts.io
url: 'https://thoughtworksarts.io'
author:
  name: Andrew McWilliams
  email: andy@jahya.net

display-banner: false
banner-url: /open-call/2019-democratization-ai-blockchain/
banner-text: "Open Call: Blockchain & AI"

# Grunt handles images and assets.
exclude: ['images', 'stylesheets', 'javascript', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true
excerpt_separator: <!--excerpt-ends-->

pagination:
  enabled: true
  sort_reverse: true
  collection: posts
  per_page: 7
  permalink: /page:num/

permalink: /blog/:title/

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate-v2

collections:
  projects:
    output: true
    permalink: /projects/:path/
  newsletters:
    output: true
    permalink: /newsletters/:slug/
  people:
    output: true
    permalink: /bio/:path/
  features:
    output: false

defaults:
  - scope:
      type: pages
    values:
      layout    : default
      bodyclass : landing-page
  - scope:
      type: posts
    values:
      layout    : post
      bodyid    : blog
      bodyclass : pattern-header-image
  - scope:
      type: newsletters
    values:
      layout    : newsletter
      bodyid    : blog
      bodyclass : pattern-header-image newsletter
  - scope:
      type: projects
    values:
      layout    : project
      bodyid    : projects
      bodyclass : pattern-header-image
  - scope:
      type: people
    values:
      layout    : bio
      bodyid    : projects
      bodyclass : pattern-header-image